{**
 * Application layout template.
 *
 * @author     Roman Sklenář
 * @package    Blog
 *}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="Nette Framework web application">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>Personal pages | {include #title|stripTags}</title>

	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/screen.css" type="text/css">
	<link rel="stylesheet" media="print" href="{$basePath}/css/print.css" type="text/css">
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">

	<script type="text/javascript" src="{$basePath}/js/jquery.min.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.livequery.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.nette.ajax.js"></script>
	<script type="text/javascript" src="{$basePath}/js/nette-blog.js"></script>
</head>

<body>
	{snippet:flashes}
	{foreach $flashes as $flash}
	<div class="flash {$flash->type}">{$flash->message}</div>
	{/foreach}
	{/snippet}

	<div>
	<div id="menu" style="float: left; width: 15%">
		<ul>
		{foreach $menu as $url => $title}
		<li><a href="{link $url 'id' => NULL}">{$title}</a></li>
		{/foreach}
		</ul>

		{if $user->isAuthenticated()}
		<small>
			<p style="text-align: center">Logged as {$user->getIdentity()->username} | <a href="{link Auth:logout}">Logout</a></p>
		</small>
		{/if}
	</div>

	<div id="content" style="float: right; width: 80%">
	{include #content}
	</div>
	</div>
</body>
</html>
